
# Línea principal del prompt
format = "$username@$hostname $directory $git_branch$git_status$line_break$character"
add_newline = true

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

[username]
show_always = true
format = "[$user]($style)"
style_user = "bold cyan"

[hostname]
ssh_only = false
format = "[$hostname]($style)"
style = "bold green"

[directory]
truncation_length = 3
truncate_to_repo = false


[git_branch]
symbol = "🚬"
style = "bold purple"
format = "[$symbol$branch]($style) "

[git_status]
style = "bold red"
staged = "[++$count](green)"
modified = "[!$count](yellow)"
untracked = "[?$count](blue)"
conflicted = "[✖ $count](red)"
ahead = "⇡$count"
behind = "⇣$count"
diverged = "⇕⇡$ahead_count⇣$behind_count"
stashed = "[📦](cyan)"
format = "([$all_status$ahead_behind]($style)) "

[line_break]
disabled = false

